In [1]:
from pgan import PGAN

In [2]:
d_path = '../../../Dataset/cifar-10-batches-py/data*'
save_path = '../../results/20190403/Experiment_005/'

In [3]:
gan = PGAN(d_path, save_path)
gan.train(4, [512, 256, 128, 64])

Network initialized
Started training 1 layers
generator output (?, 4, 4, 3)


100%|███████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.15s/it]


Finished training 1 layers
Started training 2 layers
generator output (?, 8, 8, 3)
initial:  [[ 0.01627778 -0.01674452  0.01043557 ... -0.02640498 -0.0264512
   0.00420085]
 [ 0.01615648  0.0114192   0.01182546 ...  0.02106493  0.01846038
   0.00822887]
 [ 0.01435498 -0.00965047  0.0028567  ... -0.0090045   0.01722494
   0.00938733]
 ...
 [-0.02378402 -0.01862716 -0.01653339 ... -0.01332944  0.01884616
   0.01785912]
 [-0.00969162  0.00925302 -0.00822837 ... -0.02566408 -0.00513416
   0.02312094]
 [-0.00507911 -0.00042154 -0.02127704 ... -0.00088864  0.02446131
  -0.00831106]]
after load:  [[-0.02915944 -0.0152482   0.0011044  ...  0.00753426 -0.02083318
  -0.00210802]
 [ 0.0055627  -0.01879718  0.00388756 ...  0.02484695 -0.0098967
  -0.01734124]
 [ 0.01788955 -0.01283811  0.01878114 ... -0.01246418  0.01643922
   0.01232203]
 ...
 [-0.02766256 -0.00158256 -0.00974798 ...  0.01279079 -0.02280618
  -0.0366733 ]
 [-0.01362764 -0.02481271 -0.0385293  ...  0.02482144  0.0115789
   0.00380

    -0.01050582]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.

 -4.05017752e-03 -2.25080014e-03 -3.51756020e-03  5.89982513e-03]
initial:  [[[[-4.77032736e-04  2.58053076e-02  1.31054353e-02 ... -2.51767505e-02
    -2.69480627e-02  9.70235094e-04]
   [-9.32365656e-04  2.82748174e-02 -7.93118775e-03 ... -2.32967343e-02
    -2.81228423e-02 -2.91508604e-02]
   [-2.87919175e-02  1.37280021e-02  1.11971032e-02 ... -1.14269443e-02
     2.91596819e-02 -2.65738405e-02]
   ...
   [-1.24435965e-02  6.60533272e-03  1.92730743e-02 ... -3.00760567e-03
    -4.75310348e-03  2.15169434e-02]
   [-9.55669954e-03 -1.32230856e-03  4.36521135e-03 ... -1.46648474e-03
    -4.85199504e-03  2.53648218e-02]
   [-1.42160831e-02 -2.26108152e-02  1.83472764e-02 ... -1.65097639e-02
     2.56322511e-03  6.09067641e-03]]

  [[ 1.00539494e-02  1.71339232e-02  1.97753776e-02 ...  2.83852033e-03
    -2.55435891e-03  1.26106460e-02]
   [ 1.46174263e-02  1.93421450e-02  2.03734133e-02 ...  1.11645516e-02
    -9.56269167e-03 -1.58782639e-02]
   [ 1.29760988e-03  1.22947153e-02  1.5004

     1.15427971e-02 -7.13729858e-03]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[ 1.17454156e-01 -1.74197704e-02 -7.50677288e-02]
   [-9.95603204e-02  1.21981069e-01 -9.86115187e-02]
   [ 7.80744106e-02  8.80994350e-02  5.08584529e-02]
   [-3.11782062e-02  1.65960476e-01 -1.98159903e-01]
   [ 1.16829351e-01  5.19877821e-02  1.20712861e-01]
   [-5.26945889e-02 -2.12728262e-01  1.34847954e-01]
   [ 2.03397378e-01  9.88344103e-02 -1.17893279e-01]
   [ 1.52277365e-01 -1.42126322e-01  2.09952816e-01]
   [-2.09720865e-01  6.02978319e-02  1.29583791e-01]
   [-3.15089524e-02 -5.48355281e-02 -1.78536534e-01]
   [ 4.76088971e-02

    -0.04148986]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[-0.09246432 -0.0789164   0.0095204  ...  0.00744827 -0.05477957
    -0.02684341]
   [-0.05438733 -0.02451214 -0.05375581 ...  0.01761345 -0.06837042
    -0.00408766]
   [-0.084

    -1.01886075e-02  2.63988543e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

     0.03641567]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.

  8.85182805e-03  6.20007515e-03 -1.67737133e-03  6.09122962e-03]
initial:  [[[[-5.45637123e-03 -1.00597134e-02 -1.48244817e-02 ... -6.95889443e-03
    -1.20307487e-02  1.47495251e-02]
   [ 1.72243882e-02 -5.48079424e-03  6.43902086e-03 ... -9.36547387e-03
     2.81159021e-03  7.65659288e-03]
   [-1.59065723e-02 -8.05856008e-03  1.85115635e-03 ...  2.60718539e-03
     1.23199131e-02 -1.43499244e-02]
   ...
   [ 1.26154143e-02  3.90314497e-03  1.53612159e-03 ... -1.39682088e-02
    -7.24028889e-03  8.88182782e-03]
   [ 4.01087105e-03  1.34349745e-02 -7.83770625e-03 ... -3.32916901e-03
    -1.52253546e-03 -4.18010820e-03]
   [-2.65739858e-04 -5.83164860e-03 -7.50856102e-03 ... -1.64266974e-02
    -1.60611290e-02  1.89835262e-02]]

  [[ 8.96948762e-03  5.03251702e-03  8.82842764e-03 ... -1.14695579e-02
    -7.57366326e-03 -1.56895965e-02]
   [ 8.74780864e-03 -2.34141760e-03 -1.26080513e-02 ... -1.00573087e-02
    -1.58123896e-02  7.10950792e-03]
   [-1.47281215e-02  4.68079187e-03  5.4382

     7.86705688e-03 -1.78372264e-02]]]]
after load:  [[[[ 5.62417600e-03 -4.40254778e-04 -4.27055778e-03 ...  2.97683757e-04
     1.84420347e-02  2.87148729e-03]
   [ 2.16775257e-02 -2.32502893e-02 -1.67045258e-02 ...  7.09376764e-05
     2.09212229e-02  1.77535007e-03]
   [ 2.57185977e-02  3.01295216e-03  1.48496209e-02 ...  1.31805995e-02
     7.56660243e-03 -7.98718166e-03]
   ...
   [-1.62294488e-02  3.02562816e-03  1.73529647e-02 ...  3.08300206e-03
    -2.46536918e-04  3.12496480e-02]
   [-1.61649752e-02  4.11108648e-03  7.36774830e-03 ... -7.95500539e-03
    -7.75584835e-04  1.97765380e-02]
   [ 3.24270502e-03  1.44867236e-02  2.64432710e-02 ... -1.93088986e-02
    -1.16331456e-03 -2.03889236e-03]]

  [[ 2.68075094e-02 -2.88049579e-02 -1.13984989e-03 ...  1.32667162e-02
     3.19465548e-02 -2.37020068e-02]
   [ 2.64626183e-02 -1.23025253e-02 -1.15739023e-02 ...  1.79411136e-02
     2.74411123e-02 -2.99446452e-02]
   [ 1.32602844e-02  6.79423800e-03 -6.26701489e-03 ...  2.1539408

     7.35476008e-03  3.20019647e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 [-1.92921609e-03]]
after load:  [[-0.02412318]
 [ 0.03064541]
 [ 0.11746854]
 [-0.0589814 ]
 [-0.08741306]
 [ 0.11129527]
 [-0.06772653]
 [ 0.03097875]
 [ 0.06186932]
 [-0.09312012]
 [ 0.03422972]
 [ 0.08118461]
 [-0.11519835]
 [ 0.10692384]
 [-0.07553148]
 [ 0.07514917]
 [-0.09966234]
 [ 0.1026625 ]
 [-0.09059456]
 [ 0.05339184]
 [ 0.02303885]
 [ 0.05417807]
 [-0.11119229]
 [ 0.03205593]
 [-0.06875405]
 [-0.08565584]
 [-0.02562763]
 [-0.04054334]
 [-0.12355833]
 [-0.10982513]
 [ 0.05614654]
 [-0.09975809]
 [-0.03080552]
 [ 0.10255189]
 [-0.03251039]
 [ 0.04899927]
 [ 0.05710902]
 [-0.02971589]
 [ 0.02088417]
 [-0.04384713]
 [ 0.0596437 ]
 [ 0.12060855]
 [ 0.10151248]
 [ 0.12109345]
 [-0.02855735]
 [-0.02574045]
 [-0.02143228]
 [-0.04783187]
 [ 0.07047211]
 [-0.01837243]
 [ 0.06543722]
 [ 0.07450065]
 [ 0.04192142]
 [ 0.10186732]
 [-0.04018811]
 [-0.02146285]
 [ 0.0312391 ]
 [ 0.04640486]
 [-0.02377237]
 [-0.08039989]
 [ 0.10999163]
 [ 0.03137398]
 [-0.05449148]
 [-0.09018396]
 [-0.01

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ..

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0

   [0. 0. 0.]]]]
initial:  [0. 0. 0.]
initial:  [0. 0. 0.]
initial:  [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]
initial:  [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]
initial:  [0. 0. 0.]
initial:  [0. 0. 0.]
initial:  0.0
initial:  0.99
initial:  [[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0.

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

100%|███████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.67s/it]


Finished training 2 layers
Started training 3 layers
generator output (?, 16, 16, 3)
initial:  [[-3.47682834e-03 -1.93711016e-02 -9.29421000e-03 ... -1.30862342e-02
  -2.10841317e-02 -2.54749600e-02]
 [-2.18629073e-02 -1.01620536e-02 -1.55567294e-02 ... -1.23447245e-02
  -8.14802945e-04  1.28345825e-02]
 [-1.66797824e-02 -1.27615128e-02  2.64252834e-02 ... -1.92568451e-02
  -1.17134536e-02 -1.12064974e-02]
 ...
 [ 1.03103034e-02 -1.71499327e-03 -6.59655780e-05 ... -1.52894920e-02
   8.49684700e-04  3.21732275e-03]
 [ 2.18687207e-02  8.68310779e-03  7.97715783e-03 ...  1.98059417e-02
  -6.37173653e-04 -1.98614746e-02]
 [ 1.18786022e-02 -2.01687869e-02  1.02159642e-02 ... -1.81444660e-02
  -1.97844598e-02  9.01763886e-03]]
after load:  [[-0.0341405  -0.02106422 -0.00290959 ...  0.00409189 -0.02851249
  -0.00771649]
 [ 0.00812038 -0.01363898  0.00761954 ...  0.0201576  -0.00902821
  -0.01593836]
 [ 0.0192803  -0.01211618  0.02114603 ... -0.01622916  0.01353554
   0.00938157]
 ...
 [-0.023

     2.60959491e-02 -1.05856275e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 -5.05097583e-03 -3.20109795e-03 -1.05941121e-03  7.35501153e-03]
initial:  [[[[-2.84417756e-02  1.88935194e-02 -2.41325554e-02 ... -2.33957171e-03
    -8.27704370e-03  3.41881998e-03]
   [-1.10237822e-02 -2.84285694e-02  2.77862083e-02 ... -1.82599053e-02
    -3.10263410e-03  1.47360060e-02]
   [ 6.82115741e-03 -9.55073535e-03 -2.61976589e-02 ...  4.70088236e-03
     2.82300916e-02 -2.59865876e-02]
   ...
   [-7.58804381e-04  2.93753687e-02 -6.35618716e-03 ... -2.12417804e-02
    -1.08726509e-02 -2.59730592e-02]
   [ 1.28498096e-02  2.19155122e-02 -1.72550958e-02 ...  1.90678034e-02
     1.16557311e-02  8.23909231e-03]
   [ 1.54561680e-02  5.70358522e-03 -2.82406155e-02 ... -3.19068506e-03
    -1.34990457e-02  2.85158698e-02]]

  [[ 1.69980340e-03 -1.81077681e-02  8.91117193e-03 ...  7.48093985e-03
     2.93905977e-02  2.45882757e-03]
   [ 2.13775281e-02  1.52191762e-02  1.09672975e-02 ...  8.83238576e-03
    -7.87062198e-03  2.00275909e-02]
   [ 2.12547053e-02  3.34608741e-03  2.1953

     0.00814235]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [-2.63511211e-05 -2.15057493e-03 -2.44311849e-03  3.78931727e-04
  1.13857444e-03  3.02424567e-04 -2.94561777e-03 -3.77284479e-03
  2.57284218e-03 -2.75684730e-03 -2.88650772e-0

    -3.12481727e-02  3.75957005e-02]]]]
after load:  [[[[ 1.38909342e-02  4.54603583e-02 -5.07725403e-03 ... -2.42352542e-02
     2.77626868e-02  3.52704315e-04]
   [-1.43383862e-02 -8.26678891e-03 -2.90917009e-02 ...  3.09655797e-02
     1.24407224e-02  2.23442633e-02]
   [-2.37772018e-02 -1.91015797e-03 -2.48198919e-02 ... -2.75030751e-02
    -3.40775251e-02 -1.74312375e-03]
   ...
   [-1.56445466e-02 -4.08206787e-03  3.15116607e-02 ... -2.45864410e-02
     2.89648287e-02  1.39255356e-02]
   [ 1.27998898e-02  3.09069846e-02  9.68903396e-03 ... -1.10785328e-02
     2.43633962e-03  2.55115926e-02]
   [-2.41123158e-02 -1.15617330e-03  1.36016896e-02 ... -2.48545576e-02
    -2.98722852e-02  5.42764086e-03]]

  [[-4.15654108e-02 -1.34615134e-03  1.63718816e-02 ...  4.75812564e-03
     3.07673379e-03 -3.94998752e-02]
   [ 6.27420889e-03 -7.74920173e-03 -3.32365595e-02 ...  1.60068814e-02
     1.54899238e-02  2.21352726e-02]
   [-1.67361610e-02  8.06721952e-03 -1.83652935e-03 ... -2.5480942

  4.26094141e-03 -2.52577849e-03  3.59625765e-03  1.87233672e-04]
initial:  [[[[ 2.59252861e-02  2.32307166e-02  4.69356254e-02 ...  2.63341963e-02
    -1.16227493e-02  3.00636590e-02]
   [ 1.20015219e-02  3.20211798e-03  2.91829184e-02 ... -4.48378697e-02
     8.59776512e-03  3.47480997e-02]
   [ 1.37945265e-02 -1.13097951e-02  2.79098749e-02 ... -1.87945329e-02
    -8.40314850e-03  1.07641034e-02]
   ...
   [ 1.95171386e-02  2.87139043e-03 -2.81133018e-02 ...  1.61629394e-02
    -3.13790664e-02 -2.89201271e-02]
   [ 2.20349282e-02  1.07397325e-02  3.23863477e-02 ... -3.84153053e-03
     3.45024392e-02 -2.38669012e-02]
   [-1.11199804e-02 -4.41458747e-02  3.43343094e-02 ...  9.80986655e-03
     3.47125679e-02 -2.13593580e-02]]

  [[ 2.38464773e-03 -2.83851195e-02 -5.09558730e-02 ... -1.87614039e-02
    -3.60267386e-02  4.04015929e-02]
   [-3.97378765e-02  3.59089300e-03  3.68238613e-03 ... -1.23055205e-02
    -1.91660225e-03  4.96031716e-02]
   [-2.86367163e-02 -1.18424557e-02 -1.2114

    -1.61507130e-02 -5.78713194e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[ 0.02892074 -0.149353   -0.21066284]
   [-0.21941581  0.11412615 -0.0282779 ]
   [ 0.02849546  0.04618976  0.19707173]
   [ 0.16851705 -0.05134247  0.13479564]
   [-0.294436    0.20234543 -0.28788003]
   [-0.17606369 -0.2508701   0.08858639]
   [-0.08002156  0.2552427   0.11646554]
   [-0.04654843 -0.02315509 -0.20004827]
   [ 0.1475054   0.20763785 -0.18460527]
   [-0.19414221 -0.03323093 -0.09127298]
   [-0.27142125  0.15227738 -0.14835727]
   [ 0.01994604 -0.15466845  0.25139624]
   [ 0.26465523 -0.11246067  0.26467025]
   [-0.00633964  0.22416312  0.15223336]
   [-0.05664943 -0.26251423  0.21643788]
   [ 0.22504234 -0.07313012  0.251804  ]
   [ 0.10346025  0.03410777  0.27131033]
   [-0.10744038 -0.07647495 -0.04549348]
   [ 0

   [-2.68605947e-02  5.62419146e-02 -4.13577259e-02]]]]
initial:  [0. 0. 0.]
initial:  [[[[ 0.17908259 -0.2088962  -0.18878764  0.10592942  0.02877994
    -0.20529366 -0.20403355 -0.14050022  0.12480922  0.1434222
    -0.06953108 -0.15165552  0.01783751  0.0549729   0.17013909
    -0.01774953  0.09021409 -0.19849774  0.12094854  0.1639895
     0.19502766  0.0322784   0.19038568  0.08925222  0.1697159
    -0.10632834 -0.02240722  0.06323899 -0.09474329 -0.05450882
    -0.13397457  0.15976019  0.10331987  0.18918096  0.21333821
    -0.10204645 -0.09519404 -0.09510674 -0.06950328 -0.0363341
     0.08691569 -0.08192497 -0.15698138 -0.08872105  0.13240702
     0.18112077 -0.05843751 -0.05741361  0.11822219 -0.20380782
     0.08611788 -0.18850008 -0.15419875 -0.19116972  0.1613941
    -0.02874565 -0.13955018  0.09150778  0.1866845   0.00336747
     0.11569197  0.16235729  0.06348874 -0.05664936  0.14473797
    -0.06174983 -0.05435416  0.02196111 -0.16687465 -0.03489862
     0.14626233  0.026

     0.03237985]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[-2.09194571e-02 -4.09841649e-02  2.72672996e-02 ... -2.64674705e-02
     3.36144641e-02  3.20961475e-02]
   [ 4.95466366e-02 -4.17131931e-03 -2.16318816e-02 ... -2.23156884e-02

    -0.04123127]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[-2.28466652e-02 -3.22685428e-02  2.88453847e-02 ...  2.05513835e-02
     1.22224055e-02  2.06767507e-02]
   [ 4.21793759e-03  4.81021404e-03  4.59268317e-03 ...  2.65842229e-02

    -0.02222527]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [-3.05921631e-03  4.03488614e-03 -4.14083106e-03 -2.90076854e-03
 -8.82972206e-04 -7.83100491e-04 -3.45911016e-03 -3.53139336e-03
 -4.37466148e-03  3.80380219e-03 -3.65010835e-0

    -1.18801501e-02  1.82446670e-02]]]]
after load:  [[[[ 0.00646905 -0.0047394  -0.02487802 ...  0.01610527 -0.02252447
    -0.00563469]
   [ 0.01115852 -0.01737067 -0.01656491 ...  0.00097922  0.0035098
    -0.01471637]
   [-0.00224453  0.02450576  0.02731246 ...  0.0186341  -0.01785425
     0.01592336]
   ...
   [ 0.00480891  0.01952223 -0.01231396 ... -0.01487426  0.0018605
     0.02212792]
   [ 0.02889005 -0.03212315  0.00208788 ... -0.00640758 -0.01829004
     0.00213473]
   [ 0.03085633 -0.03192052 -0.01334785 ... -0.01813002  0.0103206
    -0.01433543]]

  [[ 0.02739458  0.01194157 -0.01627852 ... -0.02040592  0.00089143
    -0.0250393 ]
   [ 0.02374687  0.01924605 -0.01592056 ... -0.00554718  0.02113259
     0.01304367]
   [ 0.00072755 -0.01528831  0.0058128  ... -0.00787907 -0.01661185
     0.02750137]
   ...
   [-0.01399813  0.00710907 -0.01863797 ... -0.01219063 -0.02552205
    -0.00565358]
   [ 0.00803824  0.00721211  0.01090243 ...  0.01407098  0.01919318
     0.00345371]

  1.36582286e-03 -2.74462090e-03 -3.27043864e-03  1.55624095e-03]
initial:  [[[[-1.57527924e-02  5.61063923e-03  4.67670150e-03 ... -1.44313443e-02
     1.50519237e-02  1.00325048e-02]
   [ 1.96975954e-02 -1.99165270e-02 -1.60111245e-02 ...  9.48983058e-03
     1.15851909e-02  2.15222649e-02]
   [-1.56134777e-02 -1.54944174e-02  1.52611919e-02 ... -1.55826928e-02
     1.45366751e-02 -1.26515115e-02]
   ...
   [-6.25434704e-03  2.99453735e-04 -1.71785075e-02 ... -2.30399761e-02
    -1.66457742e-02  4.04267386e-03]
   [-1.11299939e-02  2.35873163e-02  1.95525549e-02 ...  1.56392045e-02
    -1.43800741e-02 -1.13545191e-02]
   [ 9.76135954e-04  1.42132565e-02 -2.71414034e-03 ...  1.38978176e-02
    -6.03597611e-03 -1.58856064e-03]]

  [[ 1.12761371e-02 -1.34155145e-02 -5.56344911e-03 ...  1.14223398e-02
     1.89589523e-03 -9.64079238e-03]
   [ 1.67072713e-02  2.18358822e-03  1.58349611e-03 ...  5.52612729e-03
    -2.24667452e-02 -1.49476733e-02]
   [-9.18119401e-03  2.19062343e-03  9.5697

     4.01870674e-03  5.42384051e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

  1.47766266e-02  9.42479726e-03  6.39220374e-03  1.03334896e-02]
initial:  [[[[ 0.00315775 -0.00311756  0.01757434 ...  0.00258716 -0.00055259
     0.01012577]
   [ 0.00698685  0.00014637  0.01172949 ... -0.00737315  0.00257493
    -0.01107923]
   [ 0.00822662  0.00801941  0.01655633 ... -0.0032864   0.00382281
    -0.01425748]
   ...
   [-0.0097973   0.01282319  0.01236339 ... -0.00660626  0.01046693
     0.01634383]
   [ 0.01477586 -0.00363756 -0.01881113 ...  0.00735141  0.00821974
     0.01404443]
   [ 0.00129764  0.0012453   0.01780812 ... -0.01534149 -0.01584908
     0.00337932]]

  [[ 0.01094928 -0.01870133 -0.00706444 ... -0.010351   -0.01150971
    -0.00420481]
   [ 0.00432834 -0.00493988  0.00850113 ... -0.01838146  0.00359397
    -0.01238449]
   [-0.00706784  0.0085601   0.01698478 ...  0.00540815 -0.00886817
    -0.00528534]
   ...
   [ 0.01217061 -0.00717066 -0.01671584 ...  0.00364402 -0.00691206
     0.00240972]
   [-0.00661612  0.00229958  0.01647172 ...  0.0040883  -0

    -0.01050766]]]]
after load:  [[[[ 1.39471609e-02  2.61379895e-03 -9.50866728e-04 ...  8.45114049e-03
     2.66770590e-02  6.26332266e-03]
   [ 2.78318431e-02 -2.07154602e-02 -1.37095405e-02 ...  6.14263862e-03
     2.70376150e-02  4.71235067e-03]
   [ 3.53659503e-02  7.61171570e-04  1.25020668e-02 ...  2.20400114e-02
     1.65394973e-02 -1.02800075e-02]
   ...
   [-8.36566463e-03  8.03917239e-04  1.50217842e-02 ...  1.05517209e-02
     7.31902616e-03  2.89667919e-02]
   [-1.05252154e-02  1.82532873e-02  2.18390003e-02 ... -2.36296467e-03
     4.97545628e-03  3.43823060e-02]
   [ 9.54235811e-03  1.36727495e-02  2.55350135e-02 ... -1.35388579e-02
     4.71509947e-03 -2.90543074e-03]]

  [[ 3.57679725e-02 -2.76815537e-02  2.20614602e-04 ...  2.20399443e-02
     4.07975316e-02 -2.22749151e-02]
   [ 3.25419232e-02 -1.00956745e-02 -8.93204287e-03 ...  2.39313841e-02
     3.34803648e-02 -2.73584351e-02]
   [ 2.32035369e-02  3.89035628e-03 -9.28881299e-03 ...  3.08594648e-02
     1.5638044

     9.85806249e-03  3.02059632e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 [-0.09809443]]
after load:  [[-0.02551974]
 [ 0.02905346]
 [ 0.11593998]
 [-0.0604018 ]
 [-0.08900363]
 [ 0.10978816]
 [-0.06924006]
 [ 0.02943614]
 [ 0.06034647]
 [-0.09472715]
 [ 0.03268267]
 [ 0.07966591]
 [-0.11674143]
 [ 0.10540017]
 [-0.0771544 ]
 [ 0.07365052]
 [-0.10113167]
 [ 0.10115957]
 [-0.09216196]
 [ 0.05184391]
 [ 0.02144919]
 [ 0.05264855]
 [-0.11262016]
 [ 0.03050237]
 [-0.07037725]
 [-0.08722954]
 [-0.02695973]
 [-0.04204379]
 [-0.12508163]
 [-0.11136143]
 [ 0.05461157]
 [-0.10142117]
 [-0.03228562]
 [ 0.10102201]
 [-0.03390583]
 [ 0.04745062]
 [ 0.05562148]
 [-0.03124026]
 [ 0.01930043]
 [-0.04538714]
 [ 0.05814972]
 [ 0.11911873]
 [ 0.0999814 ]
 [ 0.11960404]
 [-0.02989118]
 [-0.027084  ]
 [-0.02271875]
 [-0.04920755]
 [ 0.06894328]
 [-0.01953983]
 [ 0.06394412]
 [ 0.07299796]
 [ 0.04037749]
 [ 0.10037903]
 [-0.04168932]
 [-0.02284697]
 [ 0.02968204]
 [ 0.04485926]
 [-0.02517144]
 [-0.0819753 ]
 [ 0.10846436]
 [ 0.02980264]
 [-0.05600078]
 [-0.09178723]
 [-0.019913

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ..

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0

   [0. 0. 0.]]]]
initial:  [0. 0. 0.]
initial:  [0. 0. 0.]
initial:  0.0
initial:  0.99
initial:  [[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0

    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0.

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

100%|███████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.20s/it]


Finished training 3 layers
Started training 4 layers
generator output (?, 32, 32, 3)
initial:  [[-0.02615775 -0.01633206  0.01468803 ...  0.00031885  0.01872049
  -0.01066275]
 [-0.02431483  0.0107411   0.01159354 ...  0.01879859 -0.02308338
   0.00816837]
 [ 0.01248446 -0.00242932  0.02478859 ... -0.00584354 -0.0021081
  -0.01840483]
 ...
 [-0.01160478  0.01107106  0.01240019 ...  0.01583847  0.0081703
   0.00230524]
 [ 0.01058898 -0.01029963  0.00301124 ... -0.02425523 -0.00951932
   0.01310563]
 [ 0.01129668 -0.01764779 -0.02354722 ... -0.00709716 -0.01122288
  -0.01376494]]
after load:  [[-0.0345491  -0.01817036 -0.00299613 ...  0.00699372 -0.024118
  -0.00801008]
 [ 0.01073306 -0.00861165  0.01478453 ...  0.01250245 -0.00099758
  -0.02397462]
 [ 0.01553852 -0.00999897  0.02015417 ... -0.0234226   0.01535461
   0.00215778]
 ...
 [-0.01914976 -0.00189309 -0.01340302 ...  0.02331368 -0.03237852
  -0.03497386]
 [-0.02745808 -0.03117661 -0.04729936 ...  0.03557611 -0.00081501
   0.0051

     3.09317186e-02 -4.80776466e-03]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 -8.80858628e-04  4.05584695e-03 -2.67452048e-03  1.49499474e-03]
initial:  [[[[-0.0280161  -0.02400247 -0.00488913 ...  0.00551709  0.00217773
    -0.00875545]
   [-0.01913121 -0.0122916   0.0026021  ... -0.01176188  0.00386749
    -0.00385337]
   [-0.02646346 -0.02358685 -0.00640894 ...  0.00102592 -0.02375521
     0.0106423 ]
   ...
   [-0.00729281 -0.01574366  0.00523861 ... -0.00433947 -0.02849876
    -0.00110084]
   [-0.00907099 -0.02048268  0.00537721 ...  0.00967007 -0.00344857
    -0.00741931]
   [ 0.01802496 -0.02162345  0.02510758 ...  0.00429857 -0.00059848
     0.01521707]]

  [[-0.00413484  0.00362788  0.00385888 ...  0.00743073 -0.01886987
    -0.02187519]
   [-0.02325577 -0.00073512 -0.02030182 ...  0.00338797  0.00320045
    -0.00769107]
   [-0.00779509 -0.00578488  0.01702154 ...  0.02260554 -0.01943842
     0.00138704]
   ...
   [-0.01967019  0.02410802 -0.00911223 ...  0.02082002 -0.01788958
    -0.02068428]
   [ 0.01840952  0.02482406 -0.00053388 ...  0.01877113  0

     1.66812947e-03  1.15121845e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [-2.08207336e-03 -9.40103736e-03 -2.52759107e-03 -8.77008773e-04
 -1.39008299e-03  8.90536699e-04 -1.54048740e-03  3.28246620e-04
 -8.70715128e-04  2.9674819

     3.56329493e-02 -3.34782004e-02]]]]
after load:  [[[[ 0.0192558   0.0385185  -0.00290633 ... -0.02316079  0.03106714
    -0.00553932]
   [-0.01507008 -0.01298798 -0.03040267 ...  0.03520153  0.01857418
     0.0202417 ]
   [-0.02177244 -0.00089092 -0.02139534 ... -0.0294811  -0.02683012
    -0.00305149]
   ...
   [-0.01609254 -0.00808201  0.03135606 ... -0.01824802  0.02688021
     0.01210275]
   [ 0.01105676  0.02856675  0.00506378 ...  0.00217593 -0.00355352
     0.02369559]
   [-0.0256703  -0.00437691  0.00913016 ... -0.00970607 -0.0357525
     0.0038786 ]]

  [[-0.03612925 -0.00891665  0.01858018 ...  0.00576255  0.00169534
    -0.04505881]
   [ 0.00615387 -0.0125669  -0.03465506 ...  0.02030622  0.02115193
     0.0200797 ]
   [-0.01474355  0.00821745  0.00127428 ... -0.0280403   0.00497237
     0.02386874]
   ...
   [-0.02421042 -0.04863354 -0.02341268 ...  0.03000439 -0.00036819
    -0.01775217]
   [-0.01414694  0.01226669 -0.04419168 ...  0.03374691 -0.04090302
    -0.0184607

     0.00584981]]]]
after load:  [[[[ 3.06649897e-02  1.85419321e-02  4.23369221e-02 ...  3.04815639e-02
    -6.93797227e-03  3.58181037e-02]
   [-4.92321051e-05  8.48588999e-03  2.81759724e-02 ... -4.38274331e-02
     7.65667390e-03  2.63163745e-02]
   [ 1.58540457e-02 -1.42336236e-02  2.60532200e-02 ... -1.75348707e-02
    -6.30956935e-03  1.81386229e-02]
   ...
   [ 1.32127656e-02  6.63275179e-03 -2.51477920e-02 ...  1.67375021e-02
    -3.62455510e-02 -4.86645214e-02]
   [ 2.66942400e-02  6.12835540e-03  2.76598018e-02 ... -1.49152882e-03
     3.92292999e-02 -1.78287867e-02]
   [-1.53309200e-02 -3.85385454e-02  3.79596762e-02 ...  1.24965003e-02
     3.04337051e-02 -2.67048962e-02]]

  [[ 7.12962588e-03 -3.30684111e-02 -5.55562265e-02 ... -1.41826048e-02
    -3.13496068e-02  4.61984351e-02]
   [-5.18473163e-02  8.77583865e-03  2.74513848e-03 ... -1.24820331e-02
    -2.96219462e-03  4.12018262e-02]
   [-2.66152937e-02 -1.50594534e-02 -1.39857568e-02 ...  2.92799138e-02
    -3.4268654

 -3.6707732e-03 -1.8258303e-03  4.3518995e-03  2.0284299e-04]
initial:  [[[[-3.4488078e-02  3.2424178e-02 -3.3321496e-02 ... -4.4939794e-02
     2.1392617e-02 -5.5449814e-02]
   [ 1.9534077e-02  2.6291553e-02  2.1495838e-02 ... -3.9866269e-02
     3.5349827e-02  1.0172520e-02]
   [-3.1687573e-02 -4.9648736e-02 -3.5862431e-02 ...  4.9306881e-02
    -1.7559305e-02  4.2347211e-02]
   ...
   [ 8.2279183e-03 -4.3768618e-02  2.1444488e-02 ... -1.2961533e-02
     1.7202880e-02  2.9851001e-02]
   [-4.7651298e-02 -2.1202352e-02  5.0125543e-02 ... -5.8993511e-03
     3.6881890e-02  5.8114734e-02]
   [-1.5942819e-02  1.0461073e-02 -2.8998183e-02 ... -4.6014607e-02
    -2.0211253e-02  2.3867507e-02]]

  [[ 2.5429454e-02  4.1043472e-02  5.5757333e-02 ...  5.8045905e-02
     2.5332760e-02  1.4669631e-02]
   [-2.7065836e-02  1.4830057e-02  3.9279405e-02 ... -2.7047150e-02
    -4.6118587e-02 -4.3843668e-02]
   [ 3.9835121e-02 -6.3804574e-03  6.3991584e-03 ...  3.9206628e-02
     1.1648592e-02 -1.20740

    -0.05629179]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [-0.00322455  0.00174633 -0.00053782 -0.00431486  0.00438363  0.00097102
  0.00509126  0.00246876 -0.00188884  0.00395888  0.00438533  0.00604394
 -0.00407644  0.00191595  0.00133197 -0.00382843 -0.00224725  0.00290318
 -0.00321242  0.00392151  0.00443762 -0.00280609 -0.00225381 -0.00219613
 -0.00536504 -0.00220922  0.00446117  0.00363468 -0.00190676 -0.00305318
  0.00419801  0.00166857  0.00200949  0.00078483  0.00146963 -0.00201693
 -0.00185987  0.00149421 -0.00333655  0.00212015  0.00409819  0.00315364
 -0.00310537 -0.00294668 -0.00422268 -0.00054366 -0.00450491 -0.0044262
 -0.00463347 -0.00291689  0.00564164  0.00358994 -0.00305174  0.00391697
 -0.00162245 -0.00229746  0.00357155  0.00158477  0.00660168 -0.00442315
  0.0041211   0.00139641  0.0023

    -0.03355936]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[ 0.2673063   0.35896948 -0.01622051]
   [-0.23843364  0.3486617  -0.20467035]
   [-0.17305443  0.17043778  0.40144303]
   [-0.15571085 -0.05708659  0.30774084]
   [ 0.02634615 -0.11999696  0.21340218]
   [-0.17082189  0.23059365 -0.27119792]
   [ 0.2809318   0.09647927 -0.02977097]
   [-0.2718174   0.27432314  0.23951498]
   [-0.24327955  0.38224295  0.18687257]
   [ 0.2846687  -0.18620697  0.06671059]
   [ 0.17526546  0.1966004   0.16836664]
   [-0.35080194  0.01741022  0.23236594]
   [-0.23995276  0.11893687  0.40762863]
   [ 0.39329937  0.30908313  0.0379703 ]
   [ 0.36751017 -0.3500906   0.38858005]
   [-0.01418954 -0.1830094  -0.20838776]
   [ 0.21285686  0.2648655   0.21723309]
   [-0.3398065  -0.3941585  -0.31660342]
   [ 0.01148516 -0.13879332 -0.2884959 ]
   [-0.20171297  0.39331844  0.11618206]
   [-0.40298647 -0.14733943 -0.336682  ]


     1.79284140e-01 -1.63845718e-03 -3.71173173e-02 -1.15717486e-01]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[-0.04257025  0.06079024 -0.03264771 ... -0.0330957  -0.02261682
    -0.02749294]
   [-0.06499195 -0.02240117 -0.05701638 ...  0.05757533  0.06780574
    -0.06857812]
   [-0.00196796 -0.05897973 -0.03531518 ...  0.00916806  0.02215727
    -0.0041779 ]
   ...
   [ 0.04166038  0.03967187  0.06045973 ...  0.05055817  0.03911242
     0.02611376]
   [ 0.06729583  0.06238921  0.04130685 ... -0.05587634 -0.0456299
    -0.01275987]
   [ 0.0261383   0.00084254  0.04240428 ...  0.00520784 -0.0177622
     0.03429952]]



    -4.20497730e-03 -2.07657106e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[ 0.02265317 -0.02509449 -0.036374   ...  0.04663111  0.02330674
    -0.00589162]
   [-0.03486138 -0.00044479 -0.01916886 ...  0.03982759  0.00014558
     0.02291246]
   [ 0.01160029 -0.01952396  0.04875509 ...  0.03124566 -0.01593203
     0.03203198]
   ...
   [ 0.01033926  0.00806295  0.04661452 ... -0.02462381  0.00674522
     0.04114074]
   [ 0.03690153  0.01052891  0.02453253 ... -0.01706557 -0.04254243
     0.04389033]
   [ 0.00582505 -0.02079989  0.02225549 ...  0.00931342 -0.04141425
    -0.01289375]]

  [[-0.0451435  -0.04793756  0

     3.08798868e-02 -3.97453308e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [ 5.8867008e-04 -6.1350414e-03 -2.0957619e-03  5.9647155e-03
  5.6398674e-03 -9.4861392e-04 -7.1804662e-04  8.2381265e-03
 -3.8788118e-03  5.6231180e-03 -2.9123740e-03  6.3258405e-03
  1.6680910e-03 -3.7004429e-04  9.1534536e-03 -3.5733727e-03
  4.6271561e-03 -3.5592192e-03 -5.0537167e-03  8.6277269e-04
 -2.1626041e-03  4.9338606e-03 -1.2850019e-03  9.2671020e-03
 -2.4964451e-03 -2.7413701e-03 -4.4291634e-03  2.2768117e-03
  3.0107368e-03 -6.0038022e-03  2.5312565e-04 -5.6458903e-03
 -6.3457279e-03  2.2490248e-03 -5.3099561e-03  3.6035345e-

    -0.04352927]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after load:  [ 4.85437736e-03 -6.04937144e-04  1.54407066e-03  3.71428346e-03
 -3.24996514e-03  3.09027993e-04 -6.21931395e-03 -8.00364185e-03
  1.88804697e-03 -4.11179010e-03  3.85722378e-0

    -0.03557334]]]]
after load:  [[[[-2.39975229e-02 -4.95605133e-02 -3.75762470e-02 ... -4.31395881e-02
     2.03913711e-02  6.01761159e-04]
   [ 1.16489152e-03  1.79851446e-02 -7.30330707e-04 ...  1.98500380e-02
    -1.92762278e-02 -1.23220263e-04]
   [ 6.01691678e-02  1.40711330e-02  4.57172953e-02 ...  1.70563310e-02
    -2.27741711e-02 -3.57345603e-02]
   ...
   [-1.62541564e-03  1.55111961e-02 -3.03659355e-04 ...  6.35295082e-03
     3.67110851e-03  3.60811427e-02]
   [ 1.58103313e-02  3.38347405e-02  1.92164406e-02 ...  4.67687435e-02
    -1.21295545e-02 -2.08049547e-02]
   [ 7.22200237e-03  5.47404587e-02  1.53598972e-02 ...  4.44772355e-02
    -1.64454821e-02  2.33635511e-02]]

  [[-2.11874787e-02  5.28089050e-03 -2.95743104e-02 ... -2.08718963e-02
     3.19209285e-02 -2.39292085e-02]
   [ 1.70418788e-02  3.73758487e-02  7.30432943e-03 ...  5.78687862e-02
     5.86420298e-03  3.85270827e-03]
   [ 4.67575975e-02  4.32461724e-02  3.58133577e-02 ...  6.17647022e-02
    -2.6425994

 -1.77953113e-02 -7.70790130e-03 -2.39631860e-03  2.85500586e-02]
initial:  [[[[ 0.00122548 -0.02309718  0.02378392 ... -0.00966526 -0.01844909
     0.01478402]
   [-0.00550944  0.01944807 -0.01037849 ...  0.0080515   0.01323571
     0.00726374]
   [ 0.01227266 -0.02337733  0.02134161 ... -0.02598229  0.00504056
    -0.01618981]
   ...
   [ 0.02306847 -0.0244705  -0.02052763 ... -0.00123596 -0.01214277
     0.01565531]
   [ 0.01129996 -0.0259232   0.02178181 ...  0.01771398  0.00083268
     0.01232353]
   [ 0.02602096 -0.02107914 -0.01438234 ... -0.01844324  0.00714653
     0.01963207]]

  [[ 0.02762552  0.00443296  0.01839188 ... -0.0028431   0.01422703
    -0.01366357]
   [ 0.02880538  0.02763223  0.0062187  ... -0.00140593 -0.01163155
    -0.02366275]
   [ 0.0013016  -0.02434496  0.0173736  ...  0.01947794  0.00502217
     0.02750722]
   ...
   [-0.01647385 -0.02886191 -0.00480829 ... -0.00209344 -0.02414938
     0.0251046 ]
   [-0.0154681   0.00551734 -0.02694627 ...  0.00857146 -0

    -2.19206270e-02  1.70054547e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

  2.09733546e-02 -2.12209038e-02 -7.84903206e-03 -1.07165426e-03]
initial:  [[[[-2.34080721e-02 -6.38082065e-03 -1.21955667e-02 ...  1.34080499e-02
     2.42291018e-02  1.20917149e-02]
   [ 2.00853124e-02  4.61963750e-03  3.56554426e-03 ... -1.41595379e-02
    -1.33997966e-02  1.95549168e-02]
   [ 1.21198781e-02  1.46293566e-02 -4.81194817e-03 ...  1.36145800e-02
    -1.08340299e-02  1.85839869e-02]
   ...
   [ 1.40813366e-02 -1.36455242e-02 -5.88857569e-03 ... -1.73325613e-02
    -1.62781887e-02  1.12498701e-02]
   [ 9.92386788e-03 -2.35830527e-02  8.22377205e-03 ...  1.14681199e-02
     1.99844018e-02 -1.90578997e-02]
   [ 1.31913014e-02  6.25150278e-03 -1.90251805e-02 ... -2.31815279e-02
     5.69568947e-04  2.15564594e-02]]

  [[ 2.19000876e-02 -3.89049202e-03  1.88719295e-02 ...  2.87549011e-03
    -2.30391510e-03 -1.65517572e-02]
   [-5.25643118e-03  2.42042169e-03 -1.14968307e-02 ... -1.13762626e-02
     2.23869719e-02  1.01583451e-02]
   [-1.95145682e-02 -1.10950861e-02 -2.1870

     0.04243214]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.

    -0.00326427]]]]
after load:  [[[[ 4.05247919e-02 -2.21285429e-02 -2.56988239e-02 ...  3.44617628e-02
     5.27245142e-02 -1.85186286e-02]
   [ 5.44556230e-02 -4.51641530e-02 -3.81596535e-02 ...  3.21563557e-02
     5.30879647e-02 -1.97779275e-02]
   [ 6.43725321e-02 -1.29630957e-02 -1.17627892e-03 ...  5.02913222e-02
     4.48651910e-02 -2.39391755e-02]
   ...
   [-1.16918320e-02 -5.47593273e-03  9.06077214e-03 ...  7.07648881e-03
     4.22095694e-03  2.29042359e-02]
   [ 2.13800631e-02 -3.67733836e-03 -4.77223657e-05 ...  2.89988276e-02
     3.63801718e-02  1.24722356e-02]
   [ 1.63483550e-04  7.40511529e-03  1.95786115e-02 ... -2.27783434e-02
    -4.25937958e-03 -8.95850547e-03]]

  [[ 6.24294430e-02 -5.24433404e-02 -2.45573856e-02 ...  4.81176637e-02
     6.69069067e-02 -4.70897146e-02]
   [ 6.05616122e-02 -3.62770967e-02 -3.52937803e-02 ...  5.17017655e-02
     6.12664036e-02 -5.37111089e-02]
   [ 5.23517802e-02 -9.91715956e-03 -2.30458938e-02 ...  5.92677258e-02
     4.4109448

     1.76677238e-02  2.06245091e-02]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 [ 0.00142268]]
after load:  [[-0.05518994]
 [ 0.03681565]
 [ 0.12418143]
 [-0.09014557]
 [-0.11877266]
 [ 0.117892  ]
 [-0.09897843]
 [ 0.03738638]
 [ 0.06831395]
 [-0.12450096]
 [ 0.04057895]
 [ 0.08771154]
 [-0.14647202]
 [ 0.11350823]
 [-0.10693058]
 [ 0.08175445]
 [-0.13088015]
 [ 0.10966989]
 [-0.12195835]
 [ 0.0598267 ]
 [ 0.02875162]
 [ 0.06066353]
 [-0.14238685]
 [ 0.03830641]
 [-0.10014818]
 [-0.11702102]
 [-0.05662766]
 [-0.07177871]
 [-0.15484726]
 [-0.14112149]
 [ 0.06250358]
 [-0.1311645 ]
 [-0.06203774]
 [ 0.10926961]
 [-0.06362288]
 [ 0.05550928]
 [ 0.06373534]
 [-0.06092877]
 [ 0.02665023]
 [-0.07515329]
 [ 0.06618289]
 [ 0.12723674]
 [ 0.10802224]
 [ 0.127852  ]
 [-0.0595625 ]
 [-0.05672644]
 [-0.05236346]
 [-0.07892786]
 [ 0.07687858]
 [-0.04906312]
 [ 0.07216925]
 [ 0.08122525]
 [ 0.04826633]
 [ 0.10857834]
 [-0.07145642]
 [-0.05248639]
 [ 0.03733122]
 [ 0.05279497]
 [-0.05484074]
 [-0.11173572]
 [ 0.11654748]
 [ 0.03748367]
 [-0.08579152]
 [-0.1215751 ]
 [-0.049471

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ..

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ..

    0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0.

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
  

 0. 0. 0. 0. 0. 0. 0. 0.]
initial:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.

   [0. 0. 0. ... 0. 0. 0.]]]]
initial:  [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ..

 [0.]]
initial:  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]

100%|███████████████████████████████████████████████████████████████| 2/2 [00:24<00:00, 12.27s/it]


Finished training 4 layers


In [ ]:
def load_data(path, im_size):
    f_names = glob.glob(path)
    data, labels = [], []
    for l in f_names:
        with open(l, 'rb') as f:
            x = pickle.load(f, encoding='bytes')
        data.append(x[b'data'].reshape((-1, *im_size), order='F').swapaxes(2, 1))
        labels.extend(x[b'labels'])
    data = np.concatenate(data)
    assert(len(labels)==len(data))
    return data, labels
def save_images(x, fname):
    s = x.shape
    x = np.concatenate([v.reshape(-1, s[-2], s[-1]) for v in np.split(x, 8, axis=0)], axis=1)
    x = 255*(0.5*x + 0.5)
    x = x.astype(np.uint8)
    plt.imsave(fname, x)

In [ ]:
import glob
import pickle
from matplotlib import pyplot as plt
import numpy as np
import skimage
d, _ = load_data(d_path, [32, 32, 3])
d_1 = np.split(d[:64], 8, axis=0)
d_1 = np.concatenate([v.reshape(-1, 32, 3) for v in np.split(d[:64], 8, axis=0)], axis=1)
print(d_1.shape)
# d_1 = np.concatenate(d_1, axis=1)

print(type(d_1))
plt.imsave('test1.png', d_1)
# save_images(d_1, 'test.png')